ghost:
  build: .
  ports:
    - "8000:2368"
  volumes:
    - ./config.js:/var/lib/ghost/config.js
    - themes/:/var/lib/ghost/themes
  volumes_from:
    - ghostdata
  env_file: .env.yml

ghostdata:
  image: busybox:ubuntu-14.04
  command: "true"
  volumes:
    - /var/lib/ghost
